name: Node.js Package

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: Git-Check-Out
        uses: actions/checkout@v4

      - id: Setup-Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@${{ github.repository_owner }}'

      - id: Authenticate-with-GitHub-Package-Registry
        run: |
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - id: Clean-Install-Dependencies
        run: npm ci

      - id: Publish-Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}