name: Node.js Package

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: Git-Check-Out
        uses: actions/checkout@v4

      - id: Setup-Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/@${{github.repository_owner}}/zyntraui
          scope: '@${{ github.repository_owner }}'

      - id: Authenticate-with-GitHub-Package-Registry
        run: |
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" >> ~/.npmrc

      - id: Clean-Install-Dependencies
        run: npm ci

      - id: Publish-Package
        run: |
          npm login --scope=@Cisco248 --auth-type=legacy --registry=https://npm.pkg.github.com
          Username: ${{ github.env.NPM_USERNAME }}
          Password: ${{ github.env.NPM_PASSWORD }}
          npm adduser
          npm publish
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}